#
# https://docs.microsoft.com/en-us/azure/storage/blobs/storage-blobs-static-site-github-actions
#
# History
# 29.12.21 created
#

name: Deploy to Azure Storage

on:
  push:
    branches: [ main ]
  workflow_dispatch:


env:
  AZURE_STORAGE_NAME: 'immo'
  AZURE_CREDS: ${{ secrets.AZURE_CREDENTIALS_960640___bee040e7}}
  NODE_VERSION: '14.x'                


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: npm install, build
      run: |
        npm install
        npm run build --if-present

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v2
      with:
        name: app
        path: ./build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Azure login
      uses: azure/login@v1
      with:
          creds: ${{ env.AZURE_CREDS }}
        
    - name: download    
    - uses: actions/download-artifact@v2
      with:
        name: app
        path: ./app
          
    - name: Upload to blob storage
      uses: azure/CLI@v1
      with:
        inlineScript: |
            az storage blob upload-batch --account-name ${{env.AZURE_STORAGE_NAME}} --auth-mode key -d '$web' -s ./app
            
    - name: logout
      run: |
            az logout
      if: always()
